atlassian:
  client-id: ${JIRA_CLIENT_ID}
  client-secret: ${JIRA_CLIENT_SECRET}
  redirect-uri: ${JIRA_REDIRECT_URI:http://localhost:8080/auth/callback}
frontend:
  url: http://localhost:5173
server:
  port: ${PORT:8080}
